apiVersion: v1
kind: ServiceAccount
metadata:
  name: pensionmanager
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: pensionmanager
  namespace: default
  labels:
    app: pensionmanager
    service: pensionmanager
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: pensionmanager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pensionmanager
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pensionmanager
      version: v1
  template:
    metadata:
      labels:
        app: pensionmanager
        version: v1
    spec:
      serviceAccountName: pensionmanager
      containers:
      - image: IMAGE
        imagePullPolicy: Always
        name: pensionmanager
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: docker-registry-creds
---

