export const EmployeeDetail = {
    "requestData": {
        "processId": "1",
        "taskSeq": "",
        "processTaskSeq": "",
        "taskTranId": "",
        "requestId": "",
        "requestDesc": "",
        "initiator": "57698",
        "person_name": "Om Prakash Kumawat",
        "action": "CRE",
        "remarks": "hjkklkll",
        "payloadChangeFlag": "Y",
        "adApproveFlag": ""
    },
    "payload": {
        "personalDetails": {
            "aadharRefNo": 444450253552284,
            "adminDeptName": "Medical Education Department, Jaipur",
            "appointAuthority": "",
            "appointOrdNum": "",
            "appointmentOrderDate": "",
            "authorityOffice": "",
            "authorityOfficeId": 0,
            "bankAccountNo": "61330497295",
            "bankBranchId": 159102,
            "bankBranchName": "BURMESE COLONY,  JAIPUR",
            "bankId": 2,
            "bankName": "STATE BANK OF INDIA",
            "beltNo": "NA",
            "bloodGroupId": 5,
            "bloodGrpName": "B+",
            "comDate": "",
            "comFlag": "",
            "cpenNumber": "0",
            "cpfNo": "NA",
            "dateOfBirth": "20/07/1963",
            "departmentName": "",
            "deptId": 202,
            "deptName": "S.M.S. Medical College and Associated Group of Hospitals, Jaipur",
            "desgDescName": "Class IV / Ward Boy / Sweeper",
            "desgId": 3000,
            "disabilityCatName": "",
            "disabilityPercent": 0,
            "disable": "0",
            "disablityId": 0,
            "dor": "31-Jul-2023",
            "emailId": "",
            "employeeCode": "RJJP198517024388",
            "employeeId": 1554804,
            "epicNo": "",
            "fatherName": "PREM CHAND",
            "genderId": 1,
            "genderName": "Male",
            "govHouseAlloted": "",
            "gpfNo": "519103",
            "height": 0,
            "identificationMarks": "",
            "identyDtlsId": "",
            "ifscCode": "SBIN0031595",
            "janadharId": "",
            "janadharMemId": "",
            "jointPhotoId": "",
            "kulakMstrId": "",
            "lasCpnfNo": "",
            "maritalStatus": "Married",
            "mobileNo": "9929294734",
            "motherName": "",
            "nameEn": "RAM BABU",
            "nameHi": "",
            "nationality": "Indian",
            "officeAdress": "",
            "officeId": 34392,
            "officeName": "S R Goyal Govt Hospital,Sethi colony, Jaipur",
            "pan": "BHFPB9914D",
            "passportNo": "",
            "payCommisionName": "Seventh",
            "payCommissionId": 10,
            "payeeId": 0,
            "pliNo": "",
            "postId": "",
            "postName": "",
            "pranNumber": "NAS",
            "religionCode": "",
            "religionNameEn": "",
            "rghsNo": "",
            "selfPhotoId": "",
            "sipfNo": "547638",
            "spouseName": "SHEELA",
            "ssoId": "RJJP198517024388"
        },
        "serviceDetails": {
            "categoryOfEmployee": "",
            "commuationPercentage": 0,
            "currentDepartmentName": "S.M.S. Medical College and Associated Group of Hospitals, Jaipur",
            "currentDesignation": "Class IV / Ward Boy / Sweeper",
            "currentOfficeAddress": "",
            "dateTypes": [
                {
                    "acronym": "DOJPD",
                    "dateFormatted": "22-01-1985",
                    "dateId": 6,
                    "dateValue": "22-01-1985"
                },
                {
                    "acronym": "DOJRS",
                    "dateFormatted": "22-01-1985",
                    "dateId": 4,
                    "dateValue": "22-01-1985"
                },
                {
                    "acronym": "DOSP",
                    "dateFormatted": "01-01-2016",
                    "dateId": 10,
                    "dateValue": "01-01-2016"
                },
                {
                    "acronym": "DOJ",
                    "dateFormatted": "20-07-1995",
                    "dateId": 3,
                    "dateValue": "20-07-1995"
                }
            ],
            "deCompletionDate": "",
            "deStartDate": "",
            "deStatus": "",
            "deTypeId": "",
            "employeeId": 1554804,
            "entitlementId": 1,
            "entitlementStatus": "Benefit before 1-1-2004",
            "gajetted": "NO",
            "incomeTaxRegime": "New",
            "officeNameEn": "S R Goyal Govt Hospital,Sethi colony, Jaipur",
            "officeTypeName": "Government",
            "officerTypeId": 1,
            "optForCommutation": "No",
            "parentDepartmentName": "Medical Education Department, Jaipur",
            "payeeId": "",
            "promotionType": 2,
            "quotaId": 1,
            "quotaName": "NA",
            "serviceCatId": 5,
            "serviceCatName": "Class IV",
            "serviceNameId": 107,
            "serviceStatusId": 9,
            "serviceStatusName": "Active",
            "serviceSubcatId": 107,
            "serviceType": "Deputation",
            "serviceTypeId": 1,
            "subServiceCatName": "The Rajasthan Class IV Service"
        },
        "addressDetails": {
            "employeeAddresses": [
                {
                    "addressId": 1986486,
                    "assemblyCode": 53,
                    "commType": "C",
                    "districtId": 631,
                    "districtNameEn": "Jaipur",
                    "emailId": "",
                    "employeeCode": "RJJP198517024388",
                    "employeeId": 1554804,
                    "homeTown": "JAIPUR",
                    "houseAddress": "251,PARBAT COLONY,DELHI ROAD,JAIPUR",
                    "landLineNumber": "0",
                    "mobileNo": "9929294734",
                    "muncipalBlockNameEn": "ADARSH NAGAR",
                    "muncipalId": "0001",
                    "officeId": 34392,
                    "officeNameEn": "S R Goyal Govt Hospital,Sethi colony, Jaipur",
                    "pinCode": "112334",
                    "ruralUrban": "",
                    "stateId": 27,
                    "stateNameEn": "Rajasthan",
                    "villStreet": "0",
                    "wardId": "0003"
                },
                {
                    "addressId": 2926864,
                    "assemblyCode": 53,
                    "commType": "P",
                    "districtId": 631,
                    "districtNameEn": "Jaipur",
                    "emailId": "",
                    "employeeCode": "RJJP198517024388",
                    "employeeId": 1554804,
                    "homeTown": "JAIPUR",
                    "houseAddress": "251,PARBAT COLONY,DELHI ROAD,JAIPUR",
                    "landLineNumber": "0",
                    "mobileNo": "9929294734",
                    "muncipalBlockNameEn": "ADARSH NAGAR",
                    "muncipalId": "0001",
                    "officeId": 34392,
                    "officeNameEn": "S R Goyal Govt Hospital,Sethi colony, Jaipur",
                    "pinCode": "112334",
                    "ruralUrban": "",
                    "stateId": 27,
                    "stateNameEn": "Rajasthan",
                    "villStreet": "0",
                    "wardId": "0003"
                }
            ],
            "officeAddresses": [
                {
                    "officeAddressNameEn": "",
                    "officeId": 34392,
                    "officeNameEn": "S R Goyal Govt Hospital,Sethi colony, Jaipur"
                }
            ]
        },
        "familyDetails": [
            {
                "aadharRefernceId": "",
                "bankAccountNo": "0",
                "bankBranchId": 0,
                "bankBranchNameEn": "",
                "disabilityId": 0,
                "disabilityPercent": 0,
                "disable": "N",
                "dob": "06-Jul-1983",
                "empId": "",
                "employeeId": 1554804,
                "familyMemId": 803236,
                "genderEn": "Male",
                "genderId": 1,
                "ifscCode": "",
                "isRajGovEmployee": "N",
                "isWorking": 1,
                "janadharId": "",
                "janadharMemId": "",
                "maritalStatusId": 0,
                "maritalStatusName": "",
                "nameEn": "DEEPAK",
                "nameHi": "",
                "panNo": "",
                "relationshipId": 7,
                "relationshipTypeEn": "Son",
                "typeOfDisability": "Intellectual"
            },
            {
                "aadharRefernceId": "",
                "bankAccountNo": "0",
                "bankBranchId": 0,
                "bankBranchNameEn": "",
                "disabilityId": 0,
                "disabilityPercent": 0,
                "disable": "N",
                "dob": "05-Aug-1984",
                "empId": "",
                "employeeId": 1554804,
                "familyMemId": 803237,
                "genderEn": "Female",
                "genderId": 2,
                "ifscCode": "",
                "isRajGovEmployee": "N",
                "isWorking": 1,
                "janadharId": "",
                "janadharMemId": "",
                "maritalStatusId": 0,
                "maritalStatusName": "",
                "nameEn": "REKHA",
                "nameHi": "",
                "panNo": "",
                "relationshipId": 6,
                "relationshipTypeEn": "Daughter",
                "typeOfDisability": "Dwarfism"
            },
            {
                "aadharRefernceId": "",
                "bankAccountNo": "0",
                "bankBranchId": 0,
                "bankBranchNameEn": "",
                "disabilityId": 0,
                "disabilityPercent": 0,
                "disable": "N",
                "dob": "23-Sep-1985",
                "empId": "",
                "employeeId": 1554804,
                "familyMemId": 803238,
                "genderEn": "Female",
                "genderId": 2,
                "ifscCode": "",
                "isRajGovEmployee": "N",
                "isWorking": 1,
                "janadharId": "",
                "janadharMemId": "",
                "maritalStatusId": 0,
                "maritalStatusName": "",
                "nameEn": "MAMTA",
                "nameHi": "",
                "panNo": "",
                "relationshipId": 6,
                "relationshipTypeEn": "Daughter",
                "typeOfDisability": "Dwarfism"
            },
            {
                "aadharRefernceId": "",
                "bankAccountNo": "0",
                "bankBranchId": 0,
                "bankBranchNameEn": "",
                "disabilityId": 0,
                "disabilityPercent": 0,
                "disable": "N",
                "dob": "25-Feb-2012",
                "empId": "",
                "employeeId": 1554804,
                "familyMemId": 803428,
                "genderEn": "Female",
                "genderId": 2,
                "ifscCode": "",
                "isRajGovEmployee": "N",
                "isWorking": 1,
                "janadharId": "",
                "janadharMemId": "",
                "maritalStatusId": 0,
                "maritalStatusName": "",
                "nameEn": "SHEELA",
                "nameHi": "",
                "panNo": "",
                "relationshipId": 5,
                "relationshipTypeEn": "Wife",
                "typeOfDisability": "Locomotor"
            }
        ],
        "nominationDetails": [],
        "serviceRecords": {
            "totalServiceLength": "28 Years,0 Months,12 Days",
            "deStatus": "",
            "deType": "",
            "deStartDate": "",
            "deEndDate": "",
            "penalty": "",
            "penaltyType": "",
            "remark": "",
            "id": 1,
            "totalNoOfDays": 10238,
            "nonQualifyingServiceDate_p": "",
            "serviceRecordDetails": []
        },
        "loansAdvance": [],
        "calculationsPayDetails": {
            "averagePay": "",
            "basicPay": 37900,
            "cca": 1000,
            "da": 15918,
            "employeeId": 1554804,
            "hra": 6822,
            "npaOrNca": "",
            "payCommissionId": 10,
            "payCommissionNameEn": "Seventh",
            "payLevel": "L4",
            "payLevelId": 290,
            "personalPay": "",
            "specialPay": "",
            "mainBudgetHead": "2071-01-101-01-00",
            "gratuityBudgetHead": "2071-01-104-01-00",
            "mainBudgetHeadId": "2103",
            "gratuityBudgetHeadId": "2108",
            "pensionType": "Superanuation",
            "pensionTypeCode": "68"
        },
        "calculationsAdditionalAllowanceRecovery": {
            "addDynamicElement": [
                {
                    "recoveryType": "",
                    "recoveryAmount": "",
                    "recoveryHead": ""
                }
            ],
            "addDeduction": [
                {
                    "deductionType": "",
                    "deductionName": "",
                    "deductionAmount": "",
                    "deductionHead": ""
                }
            ],
            "addAllowanceType": [
                {
                    "allowanceType": "",
                    "allowanceName": "",
                    "allowanceAmount": "",
                    "allowanceHead": ""
                }
            ],
            "addWithHeld": [
                {
                    "withHeldType": "",
                    "withHeldName": "",
                    "withHeldAmount": "",
                    "withHeldReason": ""
                }
            ]
        },
        "calculationsPensionDetails": {
            "allowanceAmount": 0,
            "dateOfRetirment": "31-Jul-2023",
            "nintyFiveYearAdditonalAmount": 9949,
            "commutedFactor": "",
            "deductionAmount": 0,
            "lastEmolument": 39795,
            "eightyYearAdditonalAmount": 3980,
            "enhancedPensionDate": "19-Jul-2030",
            "daRate": 42,
            "enhancedPension": "19897.5",
            "netpensionAmount": 19898,
            "retirGratuity": 791125,
            "nintyYearAdditonalAmount": 7959,
            "dateOfJoin": "20-Jul-1995",
            "daAmount": 16713.9,
            "totalNonQualifyingService": "0 Years 0 Months 0 Days ",
            "hafPay": 19897.5,
            "dateOfBirth": "20-Jul-1963",
            "pensionAmount": 19898,
            "familyPension": 11938.5,
            "eightyFiveYearAdditonalAmount": 5969,
            "SixMonthlyPeriod": 56,
            "recoveryAmount": 0,
            "totalQualifyingService": "28 Years 0 Months 12 Days ",
            "netPay": 791125,
            "totalDays": 12,
            "totalQualifyingServicePrvOrg": "0 Years 0 Months 0 Days ",
            "basicPay": 39795,
            "hundredYearAdditonalAmount": 19898,
            "reducedPension": 19898,
            "totalWithheldAmount": 0,
            "status": "Success",
            "cpoDeduction": 0,
            "commutationAmount": "",
            "commutationValue": ""
        },
        "calculationsCommutationDetailsNomination": {
            "budgetHead": "",
            "budgetHeadId": "",
            "effectiveDate": "",
            "commutationAmount": "",
            "commutationFactor": "",
            "commutationValue": ""
        },
        "bankTreasuryDetails": {
            "accountNumber": "61330497295",
            "bankBranchId": 159102,
            "bankName": "STATE BANK OF INDIA",
            "branchName": "BURMESE COLONY,  JAIPUR",
            "employeeCode": 1554804,
            "ifscCode": "SBIN0031595",
            "treasuryCode": "1800",
            "treasuryName": "JAIPUR (CITY)"
        },
        "documents": [
            {
                "dmsDocId": null,
                "docName": "Marriage Certificate",
                "docTypeId": 23
            },
            {
                "dmsDocId": null,
                "docName": "Retirement Order Sanction",
                "docTypeId": 15
            },
            {
                "dmsDocId": null,
                "docName": "Pension Kit",
                "docTypeId": 34
            },
            {
                "dmsDocId": null,
                "docName": "No DE Certificate",
                "docTypeId": 17
            },
            {
                "dmsDocId": null,
                "docName": "NSDL Certificate",
                "docTypeId": 21
            },
            {
                "dmsDocId": null,
                "docName": "Bank Passbook First Page/Cancelled Cheque",
                "docTypeId": 18
            },
            {
                "dmsDocId": null,
                "docName": "Pension Set",
                "docTypeId": 35
            },
            {
                "dmsDocId": null,
                "docName": "Signature",
                "docTypeId": 20
            },
            {
                "dmsDocId": null,
                "docName": "CPF Contribution Certificate",
                "docTypeId": 22
            },
            {
                "dmsDocId": null,
                "docName": "No Dues Certificate",
                "docTypeId": 19
            },
            {
                "dmsDocId": null,
                "docName": "Government Accomodation (Form 27,27A)",
                "docTypeId": 16
            },
            {
                "dmsDocId": null,
                "docName": "Disability Certificate",
                "docTypeId": 24
            },
            {
                "dmsDocId": null,
                "docName": "FR",
                "docTypeId": 36
            }
        ],
        "conditionList": [
            {
                "condtion_type_id": "1",
                "condition": true,
                "condition_StartDate": "2023-01-31T18:30:00.000Z",
                "condition_EndDate": "2023-07-02T18:30:00.000Z",
                "condition_FromtDate": "",
                "condition_TotDate": "",
                "condition_Amount2": "",
                "condition_Amount": "534156341",
                "condition_string": "It is certified thatNoDepartmental Enquiry under rule 16 of C.C.A Rules or criminal case is pending or contemplated against the employee on dated 01-Feb-2023 as per appointing authority order No 534156341 date 01-Feb-2023 (date of submission of pension case). Copy of retirement orders and no D.E. certificate issued from the Appointing Authority are attached with e-pension set"
            },
            {
                "condition_Amount2": "",
                "condtion_type_id": "2",
                "condition": true,
                "condition_string": "Qualifying service has been computed in the e-pension set is in accordance to service verification recorded in the service book",
                "condition_StartDate": "",
                "condition_EndDate": "",
                "condition_FromtDate": "",
                "condition_TotDate": "",
                "condition_Amount": ""
            },
            {
                "condition_Amount2": "",
                "condtion_type_id": "3",
                "condition": true,
                "condition_string": "Certificate of non occupation of Government accommodation has been obtained from the Government Employee and it is certify that he/she is not in occupation of any Government accommodation and/or have not taken any articles like furniture etc. from P.W.D. Stores on rent",
                "condition_StartDate": "",
                "condition_EndDate": "",
                "condition_FromtDate": "",
                "condition_TotDate": "",
                "condition_Amount": ""
            },
            {
                "condition_Amount2": "",
                "condtion_type_id": "4",
                "condition": true,
                "condition_string": "A certificate has been obtained from the senior accounts personnel in the Office that all the fixations made from time to time are correct and the pay being drawn is also correct, the same is attached with the e-pension set",
                "condition_StartDate": "",
                "condition_EndDate": "",
                "condition_FromtDate": "",
                "condition_TotDate": "",
                "condition_Amount": ""
            },
            {
                "condition_Amount2": "",
                "condtion_type_id": "5",
                "condition": true,
                "condition_string": "Extraordinary Leave is taken on Medical Certificate, or for Higher Studies or due to Civil Commotion/natural calamities, orders of the competent authority counting the leave period for pension are recorded in the Service Book and the same have been included in the qualifying service. Extra ordinary leave is taken other than medical certificate or interruptions of service have been included as non qualifying service in e-pension set",
                "condition_StartDate": "",
                "condition_EndDate": "",
                "condition_FromtDate": "",
                "condition_TotDate": "",
                "condition_Amount": ""
            },
            {
                "condition_Amount2": "",
                "condtion_type_id": "6",
                "condition": true,
                "condition_string": "Entry to the effect that employer's share of CPF balance has been deposited in the Government Account and Transfer Entry passed by the State Insurance/Provident Fund Department, has been recorded in the Service Book.",
                "condition_StartDate": "",
                "condition_EndDate": "",
                "condition_FromtDate": "",
                "condition_TotDate": "",
                "condition_Amount": ""
            },
            {
                "condition_Amount2": "",
                "condtion_type_id": "7",
                "condition": true,
                "condition_string": "The dues of the Government recoverable from the Government servant have been shown in tentative L.P.C and recovery/ deduction has been proposed in e-pension set",
                "condition_StartDate": "",
                "condition_EndDate": "",
                "condition_FromtDate": "",
                "condition_TotDate": "",
                "condition_Amount": ""
            },
            {
                "condition_Amount2": "",
                "condtion_type_id": "8",
                "condition": true,
                "condition_StartDate": "",
                "condition_EndDate": "",
                "condition_FromtDate": "",
                "condition_TotDate": "",
                "condition_string": "It is certified that no HBA/MCA was sanctioned to him/her during entire services",
                "condition_Amount": ""
            }
        ],
        "employeeId": 1554804,
        "employeeCode": "RJJP198517024388",
        "createdByAid": "57698",
        "createdByUserId": "59963",
        "payeeId": ""
    },
    "payloadSummary": {
        "empName": "RAM BABU",
        "emp_Id": 1554804
    }
}